version: '3.5'
services:
# 默认创建test数据库和person表
  mybatis:
    image: fansin/mysql
    container_name: mysql
    environment:
      character-set-server: utf8mb4
      collation-server: utf8mb4_unicode_ci
    networks:
      network:
        ipv4_address: 172.16.0.2

networks:
  network:
    name: docker-net
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.16.0.0/16